### PR TITLE
Updated certificates

### LINKED ISSUE #3: Certificate chain is no longer valid
The certificate chain contained in api_cert_chain.crt file are no longer valid, cUrl requests now return the following error:

```
Errors:
Array
(
    [0] => cURL error: [60] SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
)
```
I've tested an updated version of the file using the latest contents of the cacert.pem file from the current PayPal SDK and it works fine. I can post it here or send on a copy of the file or submit a pull request if you want to add me as a contributor

### PR DESCRIPTION
**Pull request by SteveEdson**
Taken from Paypal PHP SDK 

https://github.com/paypal/PayPal-PHP-SDK/blob/207c2c233eaa38b4f710eb6ac50c135970614106/lib/PayPal/Core/cacert.pem

Should fix #3, however not tested.

### CODE REVIEW

**Comment by WadeShuler** [comment]
I can't merge it if it hasn't been tested. It might be a few days before I can get around to testing it.

**Comment by SteveEdson** [comment]
We have it running now and haven't had any more issues since, however, it was intermittent anyway.

I'll leave it running a bit longer and let you know if it has been successful for us.

**Comment by WadeShuler** [comment]
Ok, thanks for the update.

This was a script that I had whipped up on a project. I needed PayPal IPN and found the Quixotix one, but it hadn't been updated in ages. So this fork is still a work in progress. I will try to get some time to work on it within the next few days. In the meantime, I welcome input from the community. Anyone that knows how to code can help out, and I will merge simple fixes that I agree with. I just don't want to merge something that is iffy and have to go backwards if it didn't work.

I updated the cert when I was working on this a few weeks ago, and it threw a fit, but the original cert worked fine so I left it. Apparently now that cert is dead.

I will keep this open until we can get a solid answer.

**Comment by SteveEdson** [comment]
We've had it running for 24hrs with the new certs, and haven't had the issue since. I'd say its definitely an improvement.

**Comment by SteveEdson** [comment]
5 days without the issue now. I would definitely consider this fixed.

Thanks,

Steve

**Comment by WadeShuler** [comment]
Merged :) Thank you for your patience.

**Pull request merged**
